havit/Havit.Blazor

- Havit.Blazor.Components.Web.Tests/DataStores/DictionaryStaticDataStoreTests.cs
- Havit.Blazor.Components.Web/Services/DataStores/DictionaryStaticDataStore.cs
Getting the `Object` from `Mock` must be thread safe. Hence doing it before spinning up testing
> Fix DictionaryStaticDataStore_ManyParallelCallsShouldNotReloadData

- Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.Components.Web.Bootstrap/Tooltips/HxTooltip.cs
Fixes #16, and allows for #17 to get resolved properly in a separate PR.
- Creates a CssClass property, which the end user would assume applies to the Tooltip itself.
- Creates a SpanCssClass property, so the developer clearly sees that class is applied to the container.
- If a span is rendered, combines the current "d-inline-block" class with the `SpanCssClass` property.
- Utilizes the Bootstrap documented `data-bs` behavior to add CssClass values to the tooltip rendering.
> [HxTooltip] CssClass & SpanCssClass

- Havit.Blazor.Components.Web.Bootstrap/Havit.Blazor.Components.Web.Bootstrap.csproj
- Havit.Blazor.Components.Web.Bootstrap/JSRuntimeExtensions.cs
- Havit.Blazor.Components.Web.Bootstrap/Properties/AssemblyInfo.cs
- Havit.Blazor.Components.Web/GlobalUsings.cs
- Havit.Blazor.Components.Web/Havit.Blazor.Components.Web.csproj
- Havit.Blazor.Components.Web/JSRuntimeExtensions.cs
- Havit.Blazor.Components.Web/Properties/AssemblyInfo.cs
@jirikanda Take a look at `GetAssemblyVersionIdentifierForUri()` please. Is it the approach we want to use to get the right version info?
> JSRuntime.ImportModule() extension method

- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/Internal/HxSearchBoxItem.razor
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor.css
Fixed
1. Collapse the dropdown
2. Open a subsection (dropdown menu)
3. Close it
4. Expand, then collapse the sidebar
5. The section can't be opened
> #224 [HxSidebar] Fix subsections not opening in sidebar collapsed state

- Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.Components.Web.Bootstrap/Collapse/HxCollapse.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor.css
- Havit.Blazor.Components.Web.Bootstrap/Navigation/SidebarItemContentTemplateContext.cs
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxCollapse.js
Feature is complete except a part in `HxSidebarItem.razor` which has to be uncommented - it uses functionality that is not in master yet but resides in https://github.com/havit/Havit.Blazor/pull/246.
> [HxSidebarItem] Provide a context to the ContentTemplate indicating whether the item is expanded or collapsed #257

- Havit.Blazor.Components.Web.Bootstrap/Buttons/HxButton.razor
- Havit.Blazor.Components.Web.Bootstrap/Buttons/HxButton.razor.css
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.css
There are two classes (one for when the icon is before the text and for after the text), this was made to allow for easy customizations in case the user wanted differing margins for these two scenarios.
> [HxButton] Space between Icon and Text #260

- Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputTextArea.cs
This link is intended for IntelliSense.
> doc - HxInputTextArea - don't display link to documentation page on the documentation page

- Havit.Blazor.Components.Web.Bootstrap/Tags/Internal/HxInputTagsInternal.razor.css
Part of the box shadow was covered by the input group
> [HxInputTags] render box shadow above input groups

- Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Tags/Internal/HxInputTagsInternal.razor.cs
problem reproduce:
1. goto https://havit.blazor.eu/components/HxInputTags
2. in `Basic usage` demo, do not enter anything, press down key, error will occur
same step with `HxAutosuggest`.
this PR fix above issues
> [HxAutosuggest][HxInputTags]: fix null reference exception

- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.cs
Noticed that the text query confirmation was detected by `@onsubmit` on a `<form>` wrapping the `<input>`, which may cause issues, therefore I have modified it to confirm the text query `oninput` by checking whether the `enter` key has been pressed.
Dependant on #376.
> [HxSearchBox] Confirm text query with enter key using KeyboardEventArgs

- Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Modals/ModalSettings.cs
Currently we do not have a possibility to remove animation of HxModal.
https://getbootstrap.com/docs/5.3/components/modal/#remove-animation
This PR adds Animate bool to be able to remove the animation. Default true, no need for defaults/settings IMO.
> To add Animate parameter to HxModal to be able to remove fade animation.

- Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Modals/ModalHidingEventArgs.cs
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxModal.js
New event "OnHiding" with ability to cancel the hiding.
Usage:
```razor
<HxModal OnHiding="OnModalHidingAsync">
...
<HxButton OnClick="SubmitAsync"/>
</HxModal>
@code {
private async Task OnModalHidingAsync(ModalHidingEventArgs args)
{
if (model.IsChanged && !(await MessageBox.ConfirmAsync(...)))
args.Cancel = true;
}
private async Task SubmitAsync()
{
MyModelService.Save(model);
model.IsChanged = false;
await HideAsync(...);
}
}
```
> [HxModal] New event "OnHiding" with ability to cancel the hiding.

- BlazorAppTest/Pages/HxInputDate_Issue621_Test.razor
- Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDate.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDateRange.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor.cs
[HxInputDateRange] Bug ToInputDateRange displays the From selected date
Add FromCalendarDisplayMonth and ToCalendarDisplayMonth
The To calendar will choose the latest of the FromDate or ToCalendarDisplayMonth or if both are not set then the FromCalendarDisplayMonth
Any changes required please let me know.
> fixed #621 [HxInputDate] Add CalendarDisplayMonth

- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor.cs
As per #638
- Select all now syncs upon item selection and filter input changes
-  Select all now automatically checks if `Value` contains all items
Missed code from #617
- Removed unwanted event callbacks
> [HxMultiSelect] Select all synchronisation

- Havit.Blazor.Documentation/Model/MemberModel.cs
@hakenr currently, `HxGrid.Defaults` leads to a non-existent page, this commit adjusts the URL, so that it leads to the `GridSettings` type definition.
However, to be consistent with other links to properties, we should change the link to lead to the page of the type where the property is defined, in this example `HxGrid`.
And since we gained the support for hashed routing to named elements in .NET 8, I suggest we consider setting the Ids of members (properties, methods, ...) in the API documentation section to increase the usefulness of the links to component members.
> [docs] Fix links to defaults

- BlazorAppTest/Pages/HxSearchBoxTest.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.css
- Add css class hx-search-box-input-with-clear-icon if there is clear button.
- Add right padding if there is new css class
Fixes #505
> HxSearchBox - fix clear button padding if there is delete icon

- BlazorAppTest/Pages/HxAccordion_Issue685_Test.razor
- BlazorAppTest/Pages/HxAccordion_Issue685_test.razor
- Havit.Blazor.Components.Web.Bootstrap/Accordions/HxAccordionItem.razor
Resolves: #685
I believe the issue was caused by `HxAccordion` attempting to manually control the `show` CSS class on `HxCollapse` which is used to hide the element when not present instead of relying on `HxCollapse` to manage it on it's own. (It is likely that the `InitiallyExpanded` parameter did not exist on `HxCollapse` at the time.)
> [HxAccordion] [Possible Bug] Accordion Collapses When It Should Stay Open

- Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor
- Havit.Blazor.Components.Web.Bootstrap/Layouts/HxListLayout.razor.css
- Havit.Blazor.Documentation/Pages/Components/HxListLayoutDoc/HxListLayout_Demo_Virtualized.razor
- Havit.Blazor.Documentation/Pages/Components/HxListLayoutDoc/HxListLayout_Demo_Virtualized.razor.css
- Havit.Blazor.Documentation/Pages/Components/HxListLayoutDoc/HxListLayout_Documentation.razor
This PR implements a built in support for sticky header in HxListLayout with no additional styles needed on the consument side + docs.
> HxListLayout - Virtualized grid variant with sticky header + docs

- BlazorAppTest/Pages/ThemeColorExtensionsTest.razor
- Havit.Blazor.Components.Web.Bootstrap/ThemeColorExtensions.cs
In this PR I added ToBorderColorCss extension method to be able to get border css class based on the ThemeColor and also added subtle/emphasis variants to ToBackgroundColorCss and ToTextColorCss.
Also created TestPage at BlazorAppTest/ThemeColorExtensionsTest.
> #745 Added ToBorderColorCss + emphasis/subtle variants

- BlazorAppTest/Pages/HxSidebarTest.razor
- BlazorAppTest/Pages/HxSidebarTest.razor.css
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor
- Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebarItem.razor.css
Resolves issue with the solution of #719 where the selector would target all childrens icons as well as the parents icon.
> [HxSidebar] HighlightOnActiveChild styles are not applied when Sidebar is collapsed

- BlazorAppTest/Pages/HxInputDateTest.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.css
This PR implements changes needed for #773.
1) Adjusted component structure
2) Added styles needed for removing borders on input if InputGroup is used
3) Added HasStartInputGroupEffective bool to control the rendering of css classes needed for styling
4) Removed "hx-input-date-predefined-dates" css calss as no usage found
> To allow using CalendarIcon with InputGroups on HxInputDate

- BlazorAppTest/Pages/HxSearchBoxTest.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.nongeneric.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.css
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/SearchBoxSearchIconPlacement.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/SearchBoxSettings.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/SearchIconPlacement.cs
- Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
In this PR, i have added a SearchIconPlacement enum and adjusted the HxSearchBox to be able to set the search icon positiont o left or right.
I have also removed a condition on input where right padding was set only if cear icon was visible. The padding should be set always.
> Add search icon placement to HxSearchBox component

- Havit.Blazor.Documentation/Services/ComponentApiDocModelBuilder.cs
The summaries for the enum members weren't being retrieved according to a reliable key - the correct summaries were matched only if the enum values started from 0 and inscreased by one. In most cases it resulted in the following.
> ComponentApiDocModelBuilder - fix enum summary order

- Havit.Blazor.Components.Web.Bootstrap/Toasts/HxToast.cs
Fixes visual discrepancy between toast header and body reported in #816.
> #816 Add ThemeColor classes to toast-header

- Havit.Blazor.Documentation/Pages/Components/HxPopoverDoc/HxPopover_Demo_Dismissible.razor
- Havit.Blazor.Documentation/Pages/Components/HxPopoverDoc/HxPopover_Documentation.razor
Fixes #611 [HxPopover] Dismiss on next click is not working on macOS
Aligns the demo with the Bootstrap docs.
> HxPopover Dismiss on next click docs update

- Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor.css
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.css
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.css
- Havit.Blazor.Documentation/Pages/Components/HxAutosuggestDoc/HxAutosuggest_Documentation.razor
- Havit.Blazor.Documentation/Pages/Components/HxSearchBoxDoc/HxSearchBox_Documentation.razor
Unified the look of clear `color` in `HxSearch` and `HxAutosuggest`.
Added CSS var for setting `color` of search and clear icon with unset as default.
Updated docs.
> Unify clear button color of HxSearch and HxAutosuggest + add possibility to set icon colors via CSS vars

- BlazorAppTest/Pages/HxGrid_Issue118_Test.razor
- Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenu.razor
- Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenu.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/ContextMenus/PopperStrategy.cs
- Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Adressing Issue #118 [HxGrid] Context menu causes scrollbar
> Attribute splatting for HxContextMenu dropdown trigger element

- Havit.Blazor.Grpc.Client/GrpcClientServiceCollectionExtensions.cs
- Havit.Blazor.Grpc.Server/EndpointRouteBuilderGrpcExtensions.cs
- Havit.Blazor.Grpc.Server/GrpcServerServiceCollectionExtensions.cs
Updated
- GrpcClientServiceCollectionExtensions
- EndpointRouteBuilderGrpcExtensions
- GrpcServerServiceCollectionExtensions to support multiple assemblies for scanning data contracts and API contract attributes. Added new overloads for relevant methods with backwards compatibility
> Support multiple assemblies in Grpc extensions

- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDate.cs
Fixes #951 
The Render was using LabelType property instead of the LabelTypeEffective.
> Fixed LabelTypeEffective instead of the actual LabelType property

- Havit.Blazor.Components.Web.Bootstrap/Buttons/HxButton.razor
To resolve an issue where tooltips hang on displayed when button is clicked while hovering the icon, we hide the icon instead of remove from DOM.
> To hide icon while button is spinning instead of removing from DOM

- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxModal.js
Analogous implementation to HxOffcanvas - fixes issues where ShowAsync and HideAsync are called in quick succession.
> HxModal onAfterRenderTasksQueue for show and hide

- BlazorAppTest/Pages/HxModalTest.razor
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Modals/ModalRenderMode.cs
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxModal.js
- Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/BusinessCardValidationModal.razor
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/BusinessCardValidationModal.razor.cs
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxModal_BusinessCardValidation_Test.razor
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxModal_BusinessCardValidation_Test.razor.cs
- Removed wrapping `if (_opened)` so the root modal `div` element is always rendered
- Added `RenderMode` parameter to `HxModal` (defaults to `OpenOnly`)
- Added a repro page for the issue where modal will not properly show up after clicking the **Show** button for a second time
If the modal is not opened and `ModalRenderMode.OpenOnly` is set then the `div.modal` as well as the `div.modal-dialog` inside will render. This is because Bootstrap Modal JS utilizes both of these `divs` when `show` is called.
When I tried to not always render the `div.modal-dialog` element then this line of code would cause a crash with an Illegal invocation exception likely due to an ivalid `this._dialog` value:
https://github.com/twbs/bootstrap/blob/main/js/src/modal.js#L183
> Add RenderMode to HxModal to align HxModal with HxOffcanvas

- Havit.Blazor.Components.Web.Bootstrap/Toasts/HxToast.cs
- Havit.Blazor.Documentation/Pages/Components/HxToastDoc/HxToast_Documentation.razor
Removed `HasContrastColor() ? "text-white" : "text-dark"` logic in favor of `ToTextBackgroundColorCss`.
Fixed Toast alert markup.
> Fixes #1001 + Toasts docs Alert markup fix

- Havit.Blazor.Components.Web.Bootstrap/Chips/HxChipList.razor.css
- Havit.Blazor.Components.Web.Bootstrap/Layouts/HxListLayout.razor
- Havit.Blazor.Components.Web.Bootstrap/Layouts/HxListLayout.razor.css
- Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.lib.css
- Havit.Blazor.Documentation/Pages/Components/HxChipListDoc/HxChipList_Documentation.razor
- Havit.Blazor.Documentation/Pages/Components/HxListLayoutDoc/HxListLayout_Demo_SearchTemplate.razor
HxListLayout
- Removed utility classes in favour of css isolation
- Added space between header and chips
- Switched filter/commands template order (filter button is always last)
ChipList
- Improved remove button visual
- Added missing CSS vars to docs
- Switched spacing to gap + new CSS var
> HxListLayout and ChipList implementation and demo cleanup

- BlazorAppTest/Pages/HxPager_NoItems_Test.razor
- Havit.Blazor.Components.Web.Bootstrap/Grids/HxPager.razor
- Havit.Blazor.Components.Web.Bootstrap/Grids/HxPager.razor.cs
- Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxPagerTests/HxPager_NoItems_Test.razor
- Havit.Blazor.TestApp/Havit.Blazor.TestApp/appsettings.Development.json
Lukáš Michl informed me about a behavior of `HxPager` that doesn't seem optimal. Currently, when `TotalPages` is set to a value lower than 1, the component doesn't look user-friendly and throws an exception when any button is pressed.
In this PR, a mechanism was added that throws an exception when `TotalPages` is set to a value lower than 1, so developers immediately notice that the value passed to this parameter must be checked and modified.
`HxGrid` solves this problem by not rendering the pager at all when `TotalPages` is lower than 2.
> HxPager - throw an exception when TotalPages is less than 1

- Havit.Blazor.Grpc.Client.Tests/GrpcClientServiceCollectionExtensionsTests.cs
- Havit.Blazor.Grpc.Client/GrpcClientInfrastructureOptions.cs
- Havit.Blazor.Grpc.Client/GrpcClientServiceCollectionExtensions.cs
Added an optional parameter to provide custom factory method for the **GrpcWebHandler**.
In my case I needed to provide custom **HttpMessageHandler** to the **GrpcWebHandler**.
https://learn.microsoft.com/en-us/dotnet/maui/data-cloud/local-web-services?view=net-maui-9.0#bypass-the-certificate-security-check
> Add GrpcWebHandler factory parameter to AddGrpcClientInfrastructure methods

- Havit.Blazor.Components.Web.Bootstrap/Buttons/HxButton.razor
- Havit.Blazor.Components.Web.Bootstrap/Buttons/HxButton.razor.cs
- Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxButtonTests/HxButton_TooltipOffcanvasOverlay_Test.razor
This PR tries to solve an issue where if you have a HxButton triggering a HxOffcanvas or HxModal over it, the tooltip gets stuck over all content, specifically on touch devices.
As I did not find any built in mechanism in Bootstrap, I am adding the TooltipContainer parameter to the HxButton that together with isolation isolate helps to manually deal with such a cases.
Before:
After:
> [HxButton] To add TooltipContainer parameter to HxButton to allow rendering tooltip to a specific place

- Havit.Blazor.Components.Web.Bootstrap.Tests/Grids/HxGrid_Cancellation_Tests.cs
- Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor.cs
@jirikanda Please review. If you're good with the change, I'll go ahead and update a few other components that currently dispose the CTS (`HxAutosuggest`, `HxSearchBox`, `HxInputTags`, etc.).
Also, we could try setting `_paginationRefreshDataCancellationTokenSource` to `null` once the data load operation finishes (both QuickGrid and FluentUI-DataGrid do this so the GC can collect the CTS ASAP), though it probably won't make much of a difference.
Reference implementations:
* https://github.com/dotnet/aspnetcore/blob/0508333c3452c8064e8d1092de9de29ad3b63bf5/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/QuickGrid.razor.cs#L150
* https://github.com/microsoft/fluentui-blazor/blob/54f2645210d9c6fedf57b3afe6c849be407f24ba/src/Core/Components/DataGrid/FluentDataGrid.razor. …
> [HxGrid] removal of CTS disposal + tests

- BlazorAppTest/Pages/HxCalendar_Issue794_Test.razor
- Havit.Blazor.Components.Web.Bootstrap/Calendar/HxCalendar.razor.cs
- Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxCalendar/HxCalendar_Issue794_Test.razor
* DisplayMonth is re-evaluated everytime Value is changed by the parameter ("from outside").
* When Value is set (not null), DisplayMonth is not limited by Min/MaxDateEffective anymore.
* When Value is null, DisplayMonth is set to current month limited by Min/MaxDateEffective (not changed)
* Year selection contains DisplayMonth.Year even it is out of the Min/MaxDateEffective range.
* Move to previous/next also works in the direction to the Min/MaxDateEffective.
https://github.com/user-attachments/assets/a5a70830-67d6-4452-a0fe-ae19ad24f63b
> [HxInputDate] - When selected date year is out of the MinDate-MaxDate, year is not displayed

- BlazorAppTest/Pages/HxInputDate_Issue787_Test.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDate.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDateRange.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor.cs
HxInputDate
- HxInputDateInternal now forwards value handling to HxInputDateInternal via CurrentValueAsStringChanged.
- an enclosing `if (FieldIdentifier.Model != null)` in the HxInputDateInternal.razor.cs was removed
HxInputDateRange
- handling from/to date parts stays in HxInputDateRangeInternal
- only (the whole range) value changes are propagated from HxInputDateRangeInternal to HxInputDateRange
- HxInputDateRangeInternal still calls `EditContext.NotifyFieldChanged(_fromFieldIdentifier/_toFieldIdentifier)` (functionality not changed), this means any valid change fires NotifyFieldChanged twice (_fromFieldIdentifier/_toFieldIdentifier and the "whole" value)
- order of actions in methods calling CurrentValueChanges is perserved but can be subject of futher discussion (ie. should …
> [HxInputDate] [HxInputDateRange] Changing value causes two calls of EditContext.OnFieldChanged #787

- Havit.Blazor.Components.Web.Bootstrap/Calendar/HxCalendar.razor.cs
- Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/DateHelper.cs
Culture is used instead of UICulture where it should be used.
DateHelper - introduced in #766.
HxCalendar - I think ve should use UICulture for week and month names but Culture for date format and first day of week.
Hopefully, Culture and UICulture (AFAIR) usually share the same value.
> HxCalendar, DateHelper - Culture & UICulture consolidation

- BlazorAppTest/Pages/HxModalTest.razor
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor
- Havit.Blazor.Components.Web.Bootstrap/Modals/HxModal.razor.css
Solves #1080 
Bootstrap applies a lot of custom styling along with layout, so it is kinda _hacky_ to get rid of it. (Also because the [close button](https://getbootstrap.com/docs/5.0/components/close-button) is a custom concept, different from Bootstrap Icons.)
Perhaps the best solution, due to bootstraps decision on this, is to change the [$btn-close-bg variable](https://getbootstrap.com/docs/5.0/components/close-button/#variables) or to use a custom header and avoid reimplementing the close button (as in the current API & this PR)
> #1080 Fix modal custom icon

- BlazorAppTest/Pages/HxInputNumberTest.razor
- Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputNumber.cs
Implements #1005.
The current implementation contains a difference in event behavior between pasting a value and pressing the minus key.
Pressing the minus key behaves "standardly": the key press triggers the `input` event, and the `change` event is only triggered when the input field loses focus.
In contrast, pasting a value from the clipboard triggers the `change` event immediately.
> [HxInputNumber] Toggle value's sign on [MINUS] key
