Havit.SourceGenerators.StrongApiStringLocalizers/Havit.SourceGenerators.StrongApiStringLocalizers.csproj
Havit.SourceGenerators.StrongApiStringLocalizers/LocalizerGenerator.cs

Support for file-scoped namespaces in LocalizerGenerator.

---

Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Havit.Blazor.Components.Web.Bootstrap.csproj
Havit.Blazor.Components.Web/Havit.Blazor.Components.Web.csproj

Just multitargeting csprojs & demo usage (HxGrid).
It lookes the build works well nowadays.

.NET 6 Support (multitargeting .NET 5 + .NET 6)

---

Havit.Blazor.Components.Web.Bootstrap/Forms/HxMultiSelect.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxMultiSelectInternal.razor.css

@hakenr Do you think this is a viable solution? It achieves pointer cursor on hover but also centers the text, however that can be easily adjusted if need be.

[HxMultiSelect] Set cursor on hover to default instead of text #154

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxCollapseDoc/HxCollapse_Demo_Programming.razor
Havit.Blazor.Components.Web.Bootstrap/Collapse/HxCollapse.razor.cs

Resolves #184
@jirikanda Please review.

#184 [HxCollapse] Tracking DOM state

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxFormValueComponentRenderer.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/IFormValueComponentWithInputGroups.cs

To-Do for components not inheriting from HxComponentBase.

[HxInput] Apply input-group size for inputs with size automatically #103

---

BlazorAppTest/Pages/HxSelectTest.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/HxSelectBase.cs

[HxSelect] Cannot be used for "add next" scenario #196

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxSidebarDoc/HxSidebar_Demo_Logo.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxSidebarDoc/HxSidebar_Documentation.razor

Should I use some generic logo image, or is the demo ok with the Havit logo?

[HxSidebar] docs - missing demo of the mainstream scenario with Logo in HxSidebarBrand #253

---

Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor

[HxGrid] Columns should not allow sorting when there are no data #322

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateDoc/HxInputDate_Demo_CalendarButtons.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateDoc/HxInputDate_Demo_CalendarIcon.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateDoc/HxInputDate_Demo_ClearButton.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateDoc/HxInputDate_Documentation.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateRangeDoc/HxInputDateRange_Demo_CalendarButtons.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateRangeDoc/HxInputDateRange_Demo_ClearButton.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxInputDateRangeDoc/HxInputDateRange_Documentation.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDate.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDate.nongeneric.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputDateRange.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/InputDateRangeSettings.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/InputDateSettings.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.css
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateRangeInternal.razor.css
Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.css

#355 [HxInputDate[Range]] Move predefined dates to dropdown-menu

---

Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInputInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInputInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Internal/KeyCodes.cs
Havit.Blazor.Components.Web.Bootstrap/Tags/Internal/HxInputTagsAutosuggestInputInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Tags/Internal/HxInputTagsAutosuggestInputInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Tags/Internal/HxInputTagsInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Tags/Internal/HxInputTagsInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxAutosuggest.js
Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxInputTags.js
Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxSearchBox.js

Implemented a solution for `HxSearchBox`, will now replicate to `HxAutosuggest` and `HxInputTags`.

[HxSearchBox] [HxAutosuggest] [HxInputTags] Keyboard navigation Up/Down moves cursor in the input

---

BlazorAppTest/Pages/HxAutosuggestTest.razor
BlazorAppTest/Pages/InputsTest.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInputInternal.razor.css
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor.css

HasAnyInputGroupEnd and its logic adding "rounded-end" utility class inside HxAutosuggest structure caused issues with overriding border radiuses on inputs. I tried to get rid of it in this PR.
Tested validation, InputGroupAddons Start/End, all working.

[HxAutosuggest] Remove need of HasAnyInputGroupEnd

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.Components.Web.Bootstrap/ContextMenus/ContextMenuSettings.cs
Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenu.razor
Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenu.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Dropdowns/DropdownMenuAlignmentExtensions.cs
Havit.Blazor.Components.Web.Bootstrap/Dropdowns/HxDropdownMenu.razor.cs

Similar to the HxDropdownMenu.
It's my first time contributing, so feel free to adjust the code as you wish.
Issue #483 should be resolved by this changes.
Thank you!

HxContextMenu - MenuAlignment added

---

Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputBase.cs

Fixes #492 [HxInputBase] form-label class should not be applied if LabelType.Floating

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/DemoData/DemoDataService.cs
Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor.cs

[HxGrid] Load more pagination loads increasingly larger page instead of additional pages

---

Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxChipListDoc/HxChipList_Demo.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxChipListDoc/HxChipList_Demo_Reset.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/Pages/Components/HxChipListDoc/HxChipList_Documentation.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.xml
Havit.Blazor.Components.Web.Bootstrap/Chips/ChipListSettings.cs
Havit.Blazor.Components.Web.Bootstrap/Chips/HxChipList.razor
Havit.Blazor.Components.Web.Bootstrap/Chips/HxChipList.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Chips/HxChipList.razor.css
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputBase.cs
Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.css

#515 [HxChipList] Support for Reset button (Remove all)

---

Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.cs

[HxSearchBox] InputCssClass is not applied to the input when set

---

Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenuItem.razor
Havit.Blazor.Components.Web.Bootstrap/ContextMenus/HxContextMenuItem.razor.cs

The href seems to work without any problem with both external and internal url. created html (blazor extra comments removed)
<ul class="dropdown-menu dropdown-menu-end show" aria-labelledby="hx1c457ad80bf74b2f83ee7d07f935ac34" b-eznrxray2a="" data-popper-placement="bottom-end" style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate(0px, 26px);" data-popper-escaped="">
<li class="hx-context-menu-item" b-mo5ybhq3h9="">
<a class="dropdown-item" role="button" b-mo5ybhq3h9="">
<i class="hx-icon bi-trash hx-context-menu-item-icon"></i>Delete             		</a>
</li>
<li class="hx-context-menu-item" b-mo5ybhq3h9="">
<a class="dropdown-item" role="button" href="components/HxDynamicElement" b-mo5ybhq3h9="">
<i class="hx-icon bi-trash …

Code agreed for Issue 559

---

Havit.Blazor.Components.Web.Bootstrap/Forms/Autosuggests/Internal/HxAutosuggestInternal.razor

Resolves #565 [HxAutosuggest] differentiate between search icon and clear icon using CSS classes

To add selectors to HxAutosuggest icons

---

BlazorAppTest/Pages/HxTreeViewTest.razor
Havit.Blazor.Components.Web.Bootstrap.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.Components.Web.Bootstrap/TreeViews/HxTreeView.razor
Havit.Blazor.Components.Web.Bootstrap/TreeViews/HxTreeView.razor.cs
Havit.Blazor.Components.Web.Bootstrap/TreeViews/Internal/HxTreeViewItemInternal.razor
Havit.Blazor.Components.Web.Bootstrap/TreeViews/Internal/HxTreeViewItemInternal.razor.cs

Events for expanding and collapsing items.

---

BlazorAppTest/Pages/HxSearchBox_Issue607_Test.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/SearchBox/HxSearchBox.razor.cs
Havit.Blazor.Components.Web.Bootstrap/wwwroot/HxSearchBox.js

Implement scrolling to focused element when using keyboard navigation on HxSearchBox

---

Havit.Blazor.Components.Web.Bootstrap/Havit.Blazor.Components.Web.Bootstrap.csproj
Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebar.razor
Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebar.razor.cs
Havit.Blazor.Components.Web.Bootstrap/Navigation/HxSidebar.razor.css
Havit.Blazor.Components.Web.Bootstrap/Resources/HxSidebar.cs.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxSidebar.it-IT.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxSidebar.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxSidebar.zh-CN.resx
Havit.Blazor.Components.Web.Bootstrap/wwwroot/defaults.css
Havit.Blazor.Documentation/Pages/Components/HxSidebarDoc/HxSidebar_Demo_TogglerTemplate.razor
Havit.Blazor.Documentation/Pages/Components/HxSidebarDoc/HxSidebar_Documentation.razor
Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml

@hakenr I have implemented a new `HxSidebar` `Toggler` inspired by chat.openai.com.
It is little more minimalistic and shows a tooltip on hover.
What needs to be done
I would like to make it into next major release.

HxSidebar Toggler v2 WIP

---

Havit.Blazor.Documentation/Pages/Index.razor

Fixes #741 
Hi @hakenr this is my first PR, does my documentation changes fit the style of `master`?

741 - Fix documentation getting started for NET 8 Blazor Web App template

---

Havit.Blazor.Components.Web.Bootstrap.Smart/HxSmartComboBox.cs
Havit.Blazor.Components.Web.Bootstrap.Smart/wwwroot/smart.css
Havit.Blazor.Documentation.Server/Pages/_Layout.cshtml

1. Created styles needed to fit into Bootstrap ecosystem light+dark mode
2. Added "smartcombobox" class to the HxSmartcomobox so the styles can be scoped
3. Linked the smart.css to docs page

Added Bootstrap styles to the HxSmartcombobox

---

Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputNumber.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputNumber.nongeneric.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputText.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputTextBase.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/InputNumberSettings.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/InputTextSettings.cs
Havit.Blazor.Documentation/Pages/Components/HxInputNumberDoc/HxInputNumber_Demo_SelectOnFocus.razor
Havit.Blazor.Documentation/Pages/Components/HxInputNumberDoc/HxInputNumber_Documentation.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTextDoc/HxInputText_Demo_SelectOnFocus.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTextDoc/HxInputText_Documentation.razor
Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml

HxInputNumber.SelectOnFocusEffective has default true to preserve current behavior

Issue #852 - HxInputText, HxInputNumber - SelectOnFocus

---

Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor

* fixes #705 
* fixes #858 
Inspired by the `QuickGrid` implementation (there's still more to incorporate):
https://github.com/dotnet/aspnetcore/blob/42af9fe6ddd7c3f9cde04ac003bf97509881873b/src/Components/QuickGrid/Microsoft.AspNetCore.Components.QuickGrid/src/QuickGrid.razor#L9

[HxGrid] Defer

---

Havit.Blazor.Components.Web.Bootstrap/Grids/HxPager.razor
Havit.Blazor.Components.Web.Bootstrap/Grids/HxPager.razor.cs
Havit.Blazor.Documentation/Pages/Components/HxPagerDoc/HxPager_Demo_Customization.razor
Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml

Allows for the use of localizable text on these elements.
My first ever pull request so please be gentle with me.

Added RenderFragments for First, Prev, Next and Last elements on theHxPager component

---

Havit.Blazor.Components.Web.Bootstrap.Tests/Forms/Internal/ChipRemoveActionBuilderTests.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputBase.cs
Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/ChipRemoveActionBuilder.cs
Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxInputBaseTests/HxInputBase_GetChipRemoveAction_NestedModel_Test.razor

[HxInputBase] ChipRemoveActionBuilder

---

Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_Basic.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_Colors.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_Disabled.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_InputGroupTemplates.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_InputGroups.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_Naked.razor
Havit.Blazor.Documentation/Pages/Components/HxInputTagsDoc/HxInputTags_Demo_Naked_InputSize.razor

We're expecting Bootstrap theme colors, not Microsoft technologies :)

[doc] in HxInputTags demos, made it obvious what we're expecting

---

BlazorAppTest/Startup.cs
Havit.Blazor.Components.Web.Bootstrap/Havit.Blazor.Components.Web.Bootstrap.csproj
Havit.Blazor.Components.Web.Bootstrap/Resources/HxAutosuggest.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxCheckbox.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxChipList.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxGrid.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxInputDate.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxInputDateRange.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxInputFileDropZone.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxInputNumber.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxInputTags.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxListLayout.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxMessageBox.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxMultiSelect.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxSidebar.de-de.resx
Havit.Blazor.Components.Web.Bootstrap/Resources/HxSpinner.de-de.resx
Havit.SourceGenerators.StrongApiStringLocalizers.Tests/Global.de-de.resx

German Translation

---

Havit.Blazor.Components.Web.Bootstrap/Grids/GridInternalStateSortingItem.cs
Havit.Blazor.Components.Web.Bootstrap/Grids/GridStateResetOptions.cs
Havit.Blazor.Components.Web.Bootstrap/Grids/HxGrid.razor.cs
Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml
Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxGridTests/HxGrid_InfiniteScroll_Test.razor
Havit.Blazor.TestApp/Havit.Blazor.TestApp.Client/HxGridTests/HxGrid_Test.razor

[HxGrid] Ability to reset grid state (position?) when refreshing data (e.g. after new filter applied) - sorting

---

BlazorAppTest/Pages/HxInputNumberTest.razor
Havit.Blazor.Components.Web.Bootstrap/Forms/HxInputNumber.cs
Havit.Blazor.Documentation/XmlDoc/Havit.Blazor.Components.Web.Bootstrap.xml

Added BindEvent parameter on HxInputNumber.
Resloves #1115

To allow setting BindEvent on HxInputNumber

---

Havit.Blazor.Components.Web.Bootstrap/Modals/MessageBoxServiceExtensions.cs

Added overloads of ConfirmAsync() method for HTML-formatted text support.

[MessageBoxServiceExtensions] HTML-formatted text support.
